[env]
_.path = [
	"./lua_modules/bin"
]

[tools]
stylua = "latest"

[tasks.build]
description = "Build the CLI"
run = "luarocks build"

[tasks.test]
description = "Run tests"
run = "luarocks test"

[tasks.lint]
description = "Run linter and formatter"
run = "stylua ."
